import pandas as pd
from openpyxl import Workbook
from openpyxl import load_workbook
from openpyxl.styles import Font, Alignment
import calendar

# Create Workbook
wb = Workbook()

# Import dirty CSV file
df = pd.read_csv("dirty_cafe_sales.csv")
wb = load_workbook("clean_cafe_sales.xlsx")
dd = len(df)

print("Starting file cleaning\n")
print(f"Original rows: {dd}")

print('Standardizing "Item"...')

# Standardize unknown "Item" to "Product"
df["Item"] = df["Item"].astype(str)
df["Item"] = df["Item"].str.strip()
df["Item"] = df["Item"].replace(["", "UNKNOWN", "ERROR", " ", "nan"], "Product")

# Standardize "Quantity" to numeric data
df["Quantity"] = pd.to_numeric(df["Quantity"], errors="coerce")

# Standardize "Price Per Unit" to numeric data
df["Price Per Unit"] = pd.to_numeric(df["Price Per Unit"], errors="coerce")

# Filter empty "Total Spent"
df["Total Spent"] = pd.to_numeric(df["Total Spent"], errors="coerce")
df = df[df["Total Spent"] >= 0]

print('Standardizing "Payment Method"...')

# Standardize unknown "Payment Method" to "Not Recorded"
df["Payment Method"] = df["Payment Method"].astype(str)
df["Payment Method"] = df["Payment Method"].str.strip()
df["Payment Method"] = df["Payment Method"].replace(["", "UNKNOWN", "ERROR", " ", "nan"], "Not Recorded")

print('Standardizing "Location"...')

# Standardize unknown "Location" to "Other"
df["Location"] = df["Location"].astype(str)
df["Location"] = df["Location"].str.strip()
df["Location"] = df["Location"].replace(["", "UNKNOWN", "ERROR", " ", "nan"], "Other")

print('Standardizing "Transaction Date"...')

# Standardize unknown "Transaction Date" to empty value
df["Transaction Date"] = pd.to_datetime(df["Transaction Date"], errors="coerce").dt.normalize()

print('Sorting data by Date...')

# Sort by date
df = df.sort_values(["Transaction Date"]).reset_index(drop=True)

print(f"Rows after cleaning: {len(df)}\n")
print(f"Rows removed: {dd - len(df)}")

print("\nGenerating clean xlsx file")

# Export clean excel document
# df.to_excel("clean_cafe_sales.xlsx", index=False)

### Openpyxl Area

ws = wb.active
ws.title = "Details"

# Format
bold = Font(bold=True)
for cell in ws[1]:  # first row
    cell.font = bold
    cell.alignment = Alignment(horizontal='center')

for row in ws.iter_rows(min_row=2):
    for cell in row:  # first row
        cell.alignment = Alignment(horizontal='center')

ws.column_dimensions['A'].width = 18
ws.column_dimensions['B'].width = 15
ws.column_dimensions['C'].width = 12
ws.column_dimensions['D'].width = 15
ws.column_dimensions['E'].width = 12
ws.column_dimensions['F'].width = 18
ws.column_dimensions['G'].width = 14
ws.column_dimensions['H'].width = 18

# Data
total_sales = df['Total Spent'].sum()
top_revenue = df.groupby('Item')['Total Spent'].sum().nlargest(1).index[0]
total_items = df['Quantity'].sum()
average_ticket = df['Total Spent'].mean()
top_payment = df[df['Payment Method'] != 'Not Recorded']['Payment Method'].value_counts().idxmax()
top_location = df["Location"].value_counts().idxmax()
month_with_most_sales = df.groupby(df['Transaction Date'].dt.month)['Total Spent'].sum().idxmax()
total_transactions = df['Item'].count()

tp = round(average_ticket, 2)

summary_ws = wb.create_sheet('Summary')

summary = [
    ['Key', 'Value'],
    ['Total Revenue', f'${total_sales}'],
    ['Total Transactions', total_transactions],
    ['Average Ticket', f'${tp}'],
    ['Units Sold', total_items],
    ['Best Selling Item', str(top_revenue)],
    ['Peak Sales Month', calendar.month_name[int(month_with_most_sales)]],
    ['Top Location', top_location],
    ['Top Payment Method', top_payment],
]

for row in summary:
    summary_ws.append(row)

# Bold headers
for cell in summary_ws[1]:
    cell.font = Font(bold=True)
    cell.alignment = Alignment(horizontal='center')

for row in summary_ws.iter_rows(min_row=2):
    for cell in row:
        cell.alignment = Alignment(horizontal='center')

# Column widths
summary_ws.column_dimensions['A'].width = 28
summary_ws.column_dimensions['B'].width = 15

# Saving wb
wb.save("complete_cafe_sales.xlsx")

# Before and After cleaning generated by AI

# Load both
dirty_df = pd.read_csv("dirty_cafe_sales.csv")
clean_df = pd.read_excel("clean_cafe_sales.xlsx")

print("=" * 60)
print("COMPARISON: BEFORE vs AFTER")
print("=" * 60)

print(f"\n📊 DIMENSIONS")
print(f"{'Original:':<20} {len(dirty_df):,} rows × {len(dirty_df.columns)} columns")
print(f"{'Clean:':<20} {len(clean_df):,} rows × {len(clean_df.columns)} columns")
print(f"{'Reduction:':<20} {len(dirty_df) - len(clean_df):,} rows ({((len(dirty_df) - len(clean_df))/len(dirty_df)*100):.1f}%)")

print(f"\n🔍 COLUMN QUALITY")
for col in ['Item', 'Payment Method', 'Location', 'Transaction Date']:
    dirty_empty = dirty_df[col].isna().sum() + (dirty_df[col].astype(str).str.strip().isin(['', 'nan', 'None', 'UNKNOWN', 'ERROR'])).sum()
    clean_empty = clean_df[col].isna().sum() + (clean_df[col].astype(str).isin([''])).sum()
    
    print(f"{col:<20} {dirty_empty:>5} empty → {clean_empty:>5} empty")

print(f"\n💰 NUMERIC INTEGRITY")
print(f"{'Valid Total Spent:':<25} {(dirty_df['Total Spent'].notna()).sum():,} → {len(clean_df):,}")
print(f"{'Amount range:':<25} ${clean_df['Total Spent'].min():.2f} to ${clean_df['Total Spent'].max():.2f}")

print(f"\n📅 TEMPORAL RANGE")
clean_dates = pd.to_datetime(clean_df['Transaction Date'], errors='coerce')
print(f"{'Period covered:':<25} {clean_dates.min()} to {clean_dates.max()}")

print("\n" + "=" * 60)